# Develop override settings

url: http://localhost:4000 #http://127.0.0.1:4000/ #

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded